# Generated by Django 4.2.1 on 2023-05-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sour_acm412', '0002_comments_created_at_topics_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='summary',
            field=models.CharField(default="Example Summary: Hi, I'm [username], and I'm excited to be part of the conversation here on Sour! I enjoy sharing my thoughts and engaging with others on various topics such as [list your interests].", max_length=255),
        ),
    ]
