# Generated by Django 4.2.1 on 2023-05-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sour_acm412', '0004_alter_users_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='summary',
            field=models.CharField(default="Hi, I'm [username], and I'm excited to be part of the conversation here on Sour! I enjoy sharing my thoughts and engaging with others on various topics such as [list your interests].", max_length=255),
        ),
    ]
